name: Summarize-QT-QML-MVC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - transformers
  - invoke
  - pip
  - pip:
    - pyside6

