name: Summarize-QT-QML-MVC
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pyside6
  - transformers
  - invoke
